# Generated by Django 5.2.9 on 2025-12-02 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('purpose', models.TextField(help_text='What is the meeting about?')),
                ('start_time', models.DateTimeField(unique=True)),
                ('end_time', models.DateTimeField()),
                ('duration', models.IntegerField(choices=[(30, '30 Minutes'), (60, '60 Minutes')], default=30)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('scheduled_with', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Booked Appointments',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g., 'Weekly Working Hours' or 'Vacation Block'", max_length=200)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('A', 'Available'), ('B', 'Busy/Blocked')], default='A', help_text='A = Available (Default), B = Busy (Blocks scheduling)', max_length=1)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Availability Blocks (Your Schedule)',
            },
        ),
    ]
